-- MySQL Script generated by MySQL Workbench
-- 09/05/17 21:45:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EZ-travel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EZ-travel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EZ-travel` DEFAULT CHARACTER SET utf8 ;
USE `EZ-travel` ;

-- -----------------------------------------------------
-- Table `EZ-travel`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EZ-travel`.`customer` (
  `customer_id` INT NOT NULL,
  `email` VARCHAR(50) NULL,
  `password` VARCHAR(200) NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `birthday` DATE NULL,
  `contact_number` VARCHAR(20) NULL,
  `nic` VARCHAR(10) NULL,
  `gender` VARCHAR(20) NULL,
  `user_status` TINYINT(1) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EZ-travel`.`customer_current_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EZ-travel`.`customer_current_location` (
  `customer_id` INT NOT NULL,
  `longitude` FLOAT(10,6) NULL,
  `latitude` FLOAT(10,6) NULL,
  `update_time` DATE NULL,
  `customer_current_locationcol` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `EZ-travel`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EZ-travel`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EZ-travel`.`employee` (
  `employee_id` INT NOT NULL,
  `email` VARCHAR(50) NULL,
  `password` VARCHAR(200) NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `is_admin` TINYINT(1) NULL,
  `birthday` DATE NULL,
  `nic` VARCHAR(10) NULL,
  `contact_number` VARCHAR(20) NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EZ-travel`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EZ-travel`.`driver` (
  `driver_id` INT NOT NULL,
  `email` VARCHAR(50) NULL,
  `password` VARCHAR(200) NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `license_number` VARCHAR(20) NULL,
  `contact_number` VARCHAR(20) NULL,
  `age` INT NULL,
  `gender` VARCHAR(20) NULL,
  `driver_status` TINYINT(1) NULL,
  `confirmed_by` INT NULL,
  PRIMARY KEY (`driver_id`),
  INDEX `confirmed_by_idx` (`confirmed_by` ASC),
  CONSTRAINT `confirmed_by`
    FOREIGN KEY (`confirmed_by`)
    REFERENCES `EZ-travel`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EZ-travel`.`hire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EZ-travel`.`hire` (
  `hire_id` INT NOT NULL,
  `start_location_latitude` FLOAT(10,6) NULL,
  `start_location_longitude` FLOAT(10,6) NULL,
  `end_location_latitude` FLOAT(10,6) NULL,
  `end_location_longitude` FLOAT(10,6) NULL,
  `cost` DOUBLE NULL,
  `date` DATE NULL,
  `customer_id` INT NULL,
  `driver_id` INT NULL,
  PRIMARY KEY (`hire_id`),
  INDEX `customer_id_idx` (`customer_id` ASC),
  INDEX `driver_id_idx` (`driver_id` ASC),
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `EZ-travel`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `driver_id`
    FOREIGN KEY (`driver_id`)
    REFERENCES `EZ-travel`.`driver` (`driver_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EZ-travel`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EZ-travel`.`feedback` (
  `feedback_id` INT NOT NULL,
  `description` VARCHAR(200) NULL,
  `customer_id` INT NULL,
  `driver_id` INT NULL,
  `hire_id` INT NULL,
  PRIMARY KEY (`feedback_id`),
  INDEX `customer_id_idx` (`customer_id` ASC),
  INDEX `driver_id_idx` (`driver_id` ASC),
  INDEX `hire_id_idx` (`hire_id` ASC),
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `EZ-travel`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `driver_id`
    FOREIGN KEY (`driver_id`)
    REFERENCES `EZ-travel`.`driver` (`driver_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hire_id`
    FOREIGN KEY (`hire_id`)
    REFERENCES `EZ-travel`.`hire` (`hire_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EZ-travel`.`driver_current_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EZ-travel`.`driver_current_location` (
  `driver_id` INT NOT NULL,
  `longitude` FLOAT(10,6) NULL,
  `latitude` FLOAT(10,6) NULL,
  `update_time` TIME NULL,
  PRIMARY KEY (`driver_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EZ-travel`.`driver_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EZ-travel`.`driver_image` (
  `driver_id` INT NOT NULL,
  `driver_licence` LONGBLOB NULL,
  `revenue_licence` LONGBLOB NULL,
  `insurance` LONGBLOB NULL,
  `driver_image` LONGBLOB NULL,
  PRIMARY KEY (`driver_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
